// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataUpload.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBDataUpload {
  private PBDataUpload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .DataRecord.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .DataRecord.DataType data_type = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType getDataType();

    /**
     * <code>required bytes val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>required bytes val = 2;</code>
     */
    com.google.protobuf.ByteString getVal();
  }
  /**
   * Protobuf type {@code DataRecord}
   */
  public  static final class DataRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataRecord)
      DataRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataRecord.newBuilder() to construct.
    private DataRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataRecord() {
      dataType_ = 0;
      val_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType value = com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              val_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder.class);
    }

    /**
     * Protobuf enum {@code DataRecord.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOG = 0;</code>
       */
      LOG(0),
      /**
       * <code>BODY_STATUS = 1;</code>
       */
      BODY_STATUS(1),
      /**
       * <pre>
       *val:SleepStatusRecord
       * </pre>
       *
       * <code>SLEEP_STATUS = 2;</code>
       */
      SLEEP_STATUS(2),
      /**
       * <code>DEV_STATISTICS = 3;</code>
       */
      DEV_STATISTICS(3),
      ;

      /**
       * <code>LOG = 0;</code>
       */
      public static final int LOG_VALUE = 0;
      /**
       * <code>BODY_STATUS = 1;</code>
       */
      public static final int BODY_STATUS_VALUE = 1;
      /**
       * <pre>
       *val:SleepStatusRecord
       * </pre>
       *
       * <code>SLEEP_STATUS = 2;</code>
       */
      public static final int SLEEP_STATUS_VALUE = 2;
      /**
       * <code>DEV_STATISTICS = 3;</code>
       */
      public static final int DEV_STATISTICS_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return LOG;
          case 1: return BODY_STATUS;
          case 2: return SLEEP_STATUS;
          case 3: return DEV_STATISTICS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataRecord.DataType)
    }

    private int bitField0_;
    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .DataRecord.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .DataRecord.DataType data_type = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType result = com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType.valueOf(dataType_);
      return result == null ? com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType.LOG : result;
    }

    public static final int VAL_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString val_;
    /**
     * <code>required bytes val = 2;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes val = 2;</code>
     */
    public com.google.protobuf.ByteString getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, val_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, val_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord) obj;

      boolean result = true;
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && dataType_ == other.dataType_;
      }
      result = result && (hasVal() == other.hasVal());
      if (hasVal()) {
        result = result && getVal()
            .equals(other.getVal());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      if (hasVal()) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataRecord)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataRecord_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.dataType_ = dataType_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.dataType_ = 0;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.val_ = val_;
          to_bitField0_ |= 0x00000002;
        } else {
          result.val_ = com.google.protobuf.ByteString.EMPTY;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        if (!hasVal()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dataType_ = 0;
      /**
       * <code>required .DataRecord.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .DataRecord.DataType data_type = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType result = com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType.valueOf(dataType_);
        return result == null ? com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType.LOG : result;
      }
      /**
       * <code>required .DataRecord.DataType data_type = 1;</code>
       */
      public Builder setDataType(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .DataRecord.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString val_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes val = 2;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes val = 2;</code>
       */
      public com.google.protobuf.ByteString getVal() {
        return val_;
      }
      /**
       * <code>required bytes val = 2;</code>
       */
      public Builder setVal(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes val = 2;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataRecord)
    }

    // @@protoc_insertion_point(class_scope:DataRecord)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataRecord>
        PARSER = new com.google.protobuf.AbstractParser<DataRecord>() {
      @java.lang.Override
      public DataRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string did = 1;</code>
     */
    boolean hasDid();
    /**
     * <code>required string did = 1;</code>
     */
    java.lang.String getDid();
    /**
     * <code>required string did = 1;</code>
     */
    com.google.protobuf.ByteString
        getDidBytes();

    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> 
        getRecordsList();
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getRecords(int index);
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    int getRecordsCount();
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder> 
        getRecordsOrBuilderList();
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder getRecordsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DataSet}
   */
  public  static final class DataSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataSet)
      DataSetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataSet.newBuilder() to construct.
    private DataSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataSet() {
      did_ = "";
      records_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              did_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                records_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord>();
                mutable_bitField0_ |= 0x00000002;
              }
              records_.add(
                  input.readMessage(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          records_ = java.util.Collections.unmodifiableList(records_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.Builder.class);
    }

    private int bitField0_;
    public static final int DID_FIELD_NUMBER = 1;
    private volatile java.lang.Object did_;
    /**
     * <code>required string did = 1;</code>
     */
    public boolean hasDid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string did = 1;</code>
     */
    public java.lang.String getDid() {
      java.lang.Object ref = did_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          did_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string did = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDidBytes() {
      java.lang.Object ref = did_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        did_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDS_FIELD_NUMBER = 2;
    private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> records_;
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> getRecordsList() {
      return records_;
    }
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder> 
        getRecordsOrBuilderList() {
      return records_;
    }
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    public int getRecordsCount() {
      return records_.size();
    }
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getRecords(int index) {
      return records_.get(index);
    }
    /**
     * <pre>
     *数据记录项
     * </pre>
     *
     * <code>repeated .DataRecord records = 2;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder getRecordsOrBuilder(
        int index) {
      return records_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRecordsCount(); i++) {
        if (!getRecords(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, did_);
      }
      for (int i = 0; i < records_.size(); i++) {
        output.writeMessage(2, records_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, did_);
      }
      for (int i = 0; i < records_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, records_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet) obj;

      boolean result = true;
      result = result && (hasDid() == other.hasDid());
      if (hasDid()) {
        result = result && getDid()
            .equals(other.getDid());
      }
      result = result && getRecordsList()
          .equals(other.getRecordsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDid()) {
        hash = (37 * hash) + DID_FIELD_NUMBER;
        hash = (53 * hash) + getDid().hashCode();
      }
      if (getRecordsCount() > 0) {
        hash = (37 * hash) + RECORDS_FIELD_NUMBER;
        hash = (53 * hash) + getRecordsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataSet)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataSet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        did_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_DataSet_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.did_ = did_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.did_ = "";
        }
        if (recordsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            records_ = java.util.Collections.unmodifiableList(records_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.records_ = records_;
        } else {
          result.records_ = recordsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet.getDefaultInstance()) return this;
        if (other.hasDid()) {
          bitField0_ |= 0x00000001;
          did_ = other.did_;
          onChanged();
        }
        if (recordsBuilder_ == null) {
          if (!other.records_.isEmpty()) {
            if (records_.isEmpty()) {
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecordsIsMutable();
              records_.addAll(other.records_);
            }
            onChanged();
          }
        } else {
          if (!other.records_.isEmpty()) {
            if (recordsBuilder_.isEmpty()) {
              recordsBuilder_.dispose();
              recordsBuilder_ = null;
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recordsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordsFieldBuilder() : null;
            } else {
              recordsBuilder_.addAllMessages(other.records_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDid()) {
          return false;
        }
        for (int i = 0; i < getRecordsCount(); i++) {
          if (!getRecords(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object did_ = "";
      /**
       * <code>required string did = 1;</code>
       */
      public boolean hasDid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string did = 1;</code>
       */
      public java.lang.String getDid() {
        java.lang.Object ref = did_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            did_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string did = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDidBytes() {
        java.lang.Object ref = did_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          did_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string did = 1;</code>
       */
      public Builder setDid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        did_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string did = 1;</code>
       */
      public Builder clearDid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        did_ = getDefaultInstance().getDid();
        onChanged();
        return this;
      }
      /**
       * <code>required string did = 1;</code>
       */
      public Builder setDidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        did_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> records_ =
        java.util.Collections.emptyList();
      private void ensureRecordsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          records_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord>(records_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder> recordsBuilder_;

      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> getRecordsList() {
        if (recordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(records_);
        } else {
          return recordsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public int getRecordsCount() {
        if (recordsBuilder_ == null) {
          return records_.size();
        } else {
          return recordsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord getRecords(int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);
        } else {
          return recordsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder setRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.set(index, value);
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder setRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder addRecords(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder addRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(index, value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder addRecords(
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder addRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder addAllRecords(
          java.lang.Iterable<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord> values) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, records_);
          onChanged();
        } else {
          recordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder clearRecords() {
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public Builder removeRecords(int index) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.remove(index);
          onChanged();
        } else {
          recordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder getRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder getRecordsOrBuilder(
          int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);  } else {
          return recordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder> 
           getRecordsOrBuilderList() {
        if (recordsBuilder_ != null) {
          return recordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(records_);
        }
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder addRecordsBuilder() {
        return getRecordsFieldBuilder().addBuilder(
            com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.getDefaultInstance());
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder addRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().addBuilder(
            index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.getDefaultInstance());
      }
      /**
       * <pre>
       *数据记录项
       * </pre>
       *
       * <code>repeated .DataRecord records = 2;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder> 
           getRecordsBuilderList() {
        return getRecordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder> 
          getRecordsFieldBuilder() {
        if (recordsBuilder_ == null) {
          recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataRecordOrBuilder>(
                  records_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          records_ = null;
        }
        return recordsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataSet)
    }

    // @@protoc_insertion_point(class_scope:DataSet)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataSet>
        PARSER = new com.google.protobuf.AbstractParser<DataSet>() {
      @java.lang.Override
      public DataSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataSet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.DataSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UploadDataStartParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UploadDataStartParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *数据集个数
     * </pre>
     *
     * <code>required int32 dataset_num = 1;</code>
     */
    boolean hasDatasetNum();
    /**
     * <pre>
     *数据集个数
     * </pre>
     *
     * <code>required int32 dataset_num = 1;</code>
     */
    int getDatasetNum();
  }
  /**
   * Protobuf type {@code UploadDataStartParam}
   */
  public  static final class UploadDataStartParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UploadDataStartParam)
      UploadDataStartParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadDataStartParam.newBuilder() to construct.
    private UploadDataStartParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadDataStartParam() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadDataStartParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              datasetNum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_UploadDataStartParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_UploadDataStartParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.Builder.class);
    }

    private int bitField0_;
    public static final int DATASET_NUM_FIELD_NUMBER = 1;
    private int datasetNum_;
    /**
     * <pre>
     *数据集个数
     * </pre>
     *
     * <code>required int32 dataset_num = 1;</code>
     */
    public boolean hasDatasetNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *数据集个数
     * </pre>
     *
     * <code>required int32 dataset_num = 1;</code>
     */
    public int getDatasetNum() {
      return datasetNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDatasetNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, datasetNum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, datasetNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam) obj;

      boolean result = true;
      result = result && (hasDatasetNum() == other.hasDatasetNum());
      if (hasDatasetNum()) {
        result = result && (getDatasetNum()
            == other.getDatasetNum());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDatasetNum()) {
        hash = (37 * hash) + DATASET_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getDatasetNum();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UploadDataStartParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UploadDataStartParam)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_UploadDataStartParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_UploadDataStartParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        datasetNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.internal_static_UploadDataStartParam_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.datasetNum_ = datasetNum_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam.getDefaultInstance()) return this;
        if (other.hasDatasetNum()) {
          setDatasetNum(other.getDatasetNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDatasetNum()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int datasetNum_ ;
      /**
       * <pre>
       *数据集个数
       * </pre>
       *
       * <code>required int32 dataset_num = 1;</code>
       */
      public boolean hasDatasetNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *数据集个数
       * </pre>
       *
       * <code>required int32 dataset_num = 1;</code>
       */
      public int getDatasetNum() {
        return datasetNum_;
      }
      /**
       * <pre>
       *数据集个数
       * </pre>
       *
       * <code>required int32 dataset_num = 1;</code>
       */
      public Builder setDatasetNum(int value) {
        bitField0_ |= 0x00000001;
        datasetNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据集个数
       * </pre>
       *
       * <code>required int32 dataset_num = 1;</code>
       */
      public Builder clearDatasetNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        datasetNum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UploadDataStartParam)
    }

    // @@protoc_insertion_point(class_scope:UploadDataStartParam)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UploadDataStartParam>
        PARSER = new com.google.protobuf.AbstractParser<UploadDataStartParam>() {
      @java.lang.Override
      public UploadDataStartParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadDataStartParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadDataStartParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadDataStartParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDataUpload.UploadDataStartParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadDataStartParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadDataStartParam_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DataUpload.proto\"\216\001\n\nDataRecord\022\'\n\tdat" +
      "a_type\030\001 \002(\0162\024.DataRecord.DataType\022\013\n\003va" +
      "l\030\002 \002(\014\"J\n\010DataType\022\007\n\003LOG\020\000\022\017\n\013BODY_STA" +
      "TUS\020\001\022\020\n\014SLEEP_STATUS\020\002\022\022\n\016DEV_STATISTIC" +
      "S\020\003\"4\n\007DataSet\022\013\n\003did\030\001 \002(\t\022\034\n\007records\030\002" +
      " \003(\0132\013.DataRecord\"+\n\024UploadDataStartPara" +
      "m\022\023\n\013dataset_num\030\001 \002(\005B7\n\'com.ryeex.groo" +
      "t.lib.ble.stack.pb.entityB\014PBDataUpload"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DataRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataRecord_descriptor,
        new java.lang.String[] { "DataType", "Val", });
    internal_static_DataSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataSet_descriptor,
        new java.lang.String[] { "Did", "Records", });
    internal_static_UploadDataStartParam_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UploadDataStartParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadDataStartParam_descriptor,
        new java.lang.String[] { "DatasetNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
