// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DevApp.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBDevApp {
  private PBDevApp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code DevAppID}
   */
  public enum DevAppID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>APPID_SYSTEM_CARD = 1;</code>
     */
    APPID_SYSTEM_CARD(1),
    /**
     * <code>APPID_SYSTEM_SPORT = 2;</code>
     */
    APPID_SYSTEM_SPORT(2),
    /**
     * <code>APPID_SYSTEM_HRM = 3;</code>
     */
    APPID_SYSTEM_HRM(3),
    /**
     * <code>APPID_SYSTEM_MIJIA = 4;</code>
     */
    APPID_SYSTEM_MIJIA(4),
    /**
     * <code>APPID_SYSTEM_WEATHER = 5;</code>
     */
    APPID_SYSTEM_WEATHER(5),
    /**
     * <code>APPID_SYSTEM_DATA = 6;</code>
     */
    APPID_SYSTEM_DATA(6),
    /**
     * <code>APPID_SYSTEM_SETTING = 7;</code>
     */
    APPID_SYSTEM_SETTING(7),
    /**
     * <code>APPID_SYSTEM_ALARM = 8;</code>
     */
    APPID_SYSTEM_ALARM(8),
    ;

    /**
     * <code>APPID_SYSTEM_CARD = 1;</code>
     */
    public static final int APPID_SYSTEM_CARD_VALUE = 1;
    /**
     * <code>APPID_SYSTEM_SPORT = 2;</code>
     */
    public static final int APPID_SYSTEM_SPORT_VALUE = 2;
    /**
     * <code>APPID_SYSTEM_HRM = 3;</code>
     */
    public static final int APPID_SYSTEM_HRM_VALUE = 3;
    /**
     * <code>APPID_SYSTEM_MIJIA = 4;</code>
     */
    public static final int APPID_SYSTEM_MIJIA_VALUE = 4;
    /**
     * <code>APPID_SYSTEM_WEATHER = 5;</code>
     */
    public static final int APPID_SYSTEM_WEATHER_VALUE = 5;
    /**
     * <code>APPID_SYSTEM_DATA = 6;</code>
     */
    public static final int APPID_SYSTEM_DATA_VALUE = 6;
    /**
     * <code>APPID_SYSTEM_SETTING = 7;</code>
     */
    public static final int APPID_SYSTEM_SETTING_VALUE = 7;
    /**
     * <code>APPID_SYSTEM_ALARM = 8;</code>
     */
    public static final int APPID_SYSTEM_ALARM_VALUE = 8;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DevAppID valueOf(int value) {
      return forNumber(value);
    }

    public static DevAppID forNumber(int value) {
      switch (value) {
        case 1: return APPID_SYSTEM_CARD;
        case 2: return APPID_SYSTEM_SPORT;
        case 3: return APPID_SYSTEM_HRM;
        case 4: return APPID_SYSTEM_MIJIA;
        case 5: return APPID_SYSTEM_WEATHER;
        case 6: return APPID_SYSTEM_DATA;
        case 7: return APPID_SYSTEM_SETTING;
        case 8: return APPID_SYSTEM_ALARM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DevAppID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DevAppID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DevAppID>() {
            public DevAppID findValueByNumber(int number) {
              return DevAppID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.getDescriptor().getEnumTypes().get(0);
    }

    private static final DevAppID[] VALUES = values();

    public static DevAppID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DevAppID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DevAppID)
  }

  public interface DevAppInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevAppInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *app id
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     *app id
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code DevAppInfo}
   */
  public  static final class DevAppInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevAppInfo)
      DevAppInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevAppInfo.newBuilder() to construct.
    private DevAppInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevAppInfo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevAppInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *app id
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *app id
     * </pre>
     *
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevAppInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevAppInfo)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppInfo_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       *app id
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *app id
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *app id
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *app id
       * </pre>
       *
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevAppInfo)
    }

    // @@protoc_insertion_point(class_scope:DevAppInfo)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevAppInfo>
        PARSER = new com.google.protobuf.AbstractParser<DevAppInfo>() {
      @java.lang.Override
      public DevAppInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevAppInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevAppInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevAppInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DevAppListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevAppList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> 
        getDevAppInfosList();
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDevAppInfos(int index);
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    int getDevAppInfosCount();
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder> 
        getDevAppInfosOrBuilderList();
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder getDevAppInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DevAppList}
   */
  public  static final class DevAppList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevAppList)
      DevAppListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevAppList.newBuilder() to construct.
    private DevAppList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevAppList() {
      devAppInfos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevAppList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                devAppInfos_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              devAppInfos_.add(
                  input.readMessage(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          devAppInfos_ = java.util.Collections.unmodifiableList(devAppInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.Builder.class);
    }

    public static final int DEV_APP_INFOS_FIELD_NUMBER = 1;
    private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> devAppInfos_;
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> getDevAppInfosList() {
      return devAppInfos_;
    }
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder> 
        getDevAppInfosOrBuilderList() {
      return devAppInfos_;
    }
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    public int getDevAppInfosCount() {
      return devAppInfos_.size();
    }
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDevAppInfos(int index) {
      return devAppInfos_.get(index);
    }
    /**
     * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder getDevAppInfosOrBuilder(
        int index) {
      return devAppInfos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDevAppInfosCount(); i++) {
        if (!getDevAppInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < devAppInfos_.size(); i++) {
        output.writeMessage(1, devAppInfos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < devAppInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, devAppInfos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList) obj;

      boolean result = true;
      result = result && getDevAppInfosList()
          .equals(other.getDevAppInfosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDevAppInfosCount() > 0) {
        hash = (37 * hash) + DEV_APP_INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getDevAppInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevAppList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevAppList)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDevAppInfosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (devAppInfosBuilder_ == null) {
          devAppInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          devAppInfosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.internal_static_DevAppList_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList(this);
        int from_bitField0_ = bitField0_;
        if (devAppInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            devAppInfos_ = java.util.Collections.unmodifiableList(devAppInfos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.devAppInfos_ = devAppInfos_;
        } else {
          result.devAppInfos_ = devAppInfosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList.getDefaultInstance()) return this;
        if (devAppInfosBuilder_ == null) {
          if (!other.devAppInfos_.isEmpty()) {
            if (devAppInfos_.isEmpty()) {
              devAppInfos_ = other.devAppInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDevAppInfosIsMutable();
              devAppInfos_.addAll(other.devAppInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.devAppInfos_.isEmpty()) {
            if (devAppInfosBuilder_.isEmpty()) {
              devAppInfosBuilder_.dispose();
              devAppInfosBuilder_ = null;
              devAppInfos_ = other.devAppInfos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              devAppInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDevAppInfosFieldBuilder() : null;
            } else {
              devAppInfosBuilder_.addAllMessages(other.devAppInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDevAppInfosCount(); i++) {
          if (!getDevAppInfos(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> devAppInfos_ =
        java.util.Collections.emptyList();
      private void ensureDevAppInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          devAppInfos_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo>(devAppInfos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder> devAppInfosBuilder_;

      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> getDevAppInfosList() {
        if (devAppInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(devAppInfos_);
        } else {
          return devAppInfosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public int getDevAppInfosCount() {
        if (devAppInfosBuilder_ == null) {
          return devAppInfos_.size();
        } else {
          return devAppInfosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo getDevAppInfos(int index) {
        if (devAppInfosBuilder_ == null) {
          return devAppInfos_.get(index);
        } else {
          return devAppInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder setDevAppInfos(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo value) {
        if (devAppInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevAppInfosIsMutable();
          devAppInfos_.set(index, value);
          onChanged();
        } else {
          devAppInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder setDevAppInfos(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder builderForValue) {
        if (devAppInfosBuilder_ == null) {
          ensureDevAppInfosIsMutable();
          devAppInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          devAppInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder addDevAppInfos(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo value) {
        if (devAppInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevAppInfosIsMutable();
          devAppInfos_.add(value);
          onChanged();
        } else {
          devAppInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder addDevAppInfos(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo value) {
        if (devAppInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevAppInfosIsMutable();
          devAppInfos_.add(index, value);
          onChanged();
        } else {
          devAppInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder addDevAppInfos(
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder builderForValue) {
        if (devAppInfosBuilder_ == null) {
          ensureDevAppInfosIsMutable();
          devAppInfos_.add(builderForValue.build());
          onChanged();
        } else {
          devAppInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder addDevAppInfos(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder builderForValue) {
        if (devAppInfosBuilder_ == null) {
          ensureDevAppInfosIsMutable();
          devAppInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          devAppInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder addAllDevAppInfos(
          java.lang.Iterable<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo> values) {
        if (devAppInfosBuilder_ == null) {
          ensureDevAppInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, devAppInfos_);
          onChanged();
        } else {
          devAppInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder clearDevAppInfos() {
        if (devAppInfosBuilder_ == null) {
          devAppInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          devAppInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public Builder removeDevAppInfos(int index) {
        if (devAppInfosBuilder_ == null) {
          ensureDevAppInfosIsMutable();
          devAppInfos_.remove(index);
          onChanged();
        } else {
          devAppInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder getDevAppInfosBuilder(
          int index) {
        return getDevAppInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder getDevAppInfosOrBuilder(
          int index) {
        if (devAppInfosBuilder_ == null) {
          return devAppInfos_.get(index);  } else {
          return devAppInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder> 
           getDevAppInfosOrBuilderList() {
        if (devAppInfosBuilder_ != null) {
          return devAppInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(devAppInfos_);
        }
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder addDevAppInfosBuilder() {
        return getDevAppInfosFieldBuilder().addBuilder(
            com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder addDevAppInfosBuilder(
          int index) {
        return getDevAppInfosFieldBuilder().addBuilder(
            index, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .DevAppInfo dev_app_infos = 1;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder> 
           getDevAppInfosBuilderList() {
        return getDevAppInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder> 
          getDevAppInfosFieldBuilder() {
        if (devAppInfosBuilder_ == null) {
          devAppInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfo.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppInfoOrBuilder>(
                  devAppInfos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          devAppInfos_ = null;
        }
        return devAppInfosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevAppList)
    }

    // @@protoc_insertion_point(class_scope:DevAppList)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevAppList>
        PARSER = new com.google.protobuf.AbstractParser<DevAppList>() {
      @java.lang.Override
      public DevAppList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevAppList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevAppList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevAppList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevApp.DevAppList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevAppInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevAppInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevAppList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevAppList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014DevApp.proto\"\030\n\nDevAppInfo\022\n\n\002id\030\001 \002(\005" +
      "\"0\n\nDevAppList\022\"\n\rdev_app_infos\030\001 \003(\0132\013." +
      "DevAppInfo*\312\001\n\010DevAppID\022\025\n\021APPID_SYSTEM_" +
      "CARD\020\001\022\026\n\022APPID_SYSTEM_SPORT\020\002\022\024\n\020APPID_" +
      "SYSTEM_HRM\020\003\022\026\n\022APPID_SYSTEM_MIJIA\020\004\022\030\n\024" +
      "APPID_SYSTEM_WEATHER\020\005\022\025\n\021APPID_SYSTEM_D" +
      "ATA\020\006\022\030\n\024APPID_SYSTEM_SETTING\020\007\022\026\n\022APPID" +
      "_SYSTEM_ALARM\020\010B3\n\'com.ryeex.groot.lib.b" +
      "le.stack.pb.entityB\010PBDevApp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DevAppInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DevAppInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevAppInfo_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DevAppList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DevAppList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevAppList_descriptor,
        new java.lang.String[] { "DevAppInfos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
