// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DevLog.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBDevLog {
  private PBDevLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DevLogStartResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevLogStartResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 session_id = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required int32 session_id = 1;</code>
     */
    int getSessionId();

    /**
     * <code>required int32 total = 2;</code>
     */
    boolean hasTotal();
    /**
     * <code>required int32 total = 2;</code>
     */
    int getTotal();
  }
  /**
   * Protobuf type {@code DevLogStartResult}
   */
  public  static final class DevLogStartResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevLogStartResult)
      DevLogStartResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevLogStartResult.newBuilder() to construct.
    private DevLogStartResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevLogStartResult() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevLogStartResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              total_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogStartResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogStartResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <code>required int32 session_id = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 session_id = 1;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int TOTAL_FIELD_NUMBER = 2;
    private int total_;
    /**
     * <code>required int32 total = 2;</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 total = 2;</code>
     */
    public int getTotal() {
      return total_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, total_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, total_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult) obj;

      boolean result = true;
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasTotal() == other.hasTotal());
      if (hasTotal()) {
        result = result && (getTotal()
            == other.getTotal());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId();
      }
      if (hasTotal()) {
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevLogStartResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevLogStartResult)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogStartResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogStartResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogStartResult_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.sessionId_ = sessionId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.total_ = total_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        if (!hasTotal()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sessionId_ ;
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int total_ ;
      /**
       * <code>required int32 total = 2;</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 total = 2;</code>
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>required int32 total = 2;</code>
       */
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000002;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total = 2;</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevLogStartResult)
    }

    // @@protoc_insertion_point(class_scope:DevLogStartResult)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevLogStartResult>
        PARSER = new com.google.protobuf.AbstractParser<DevLogStartResult>() {
      @java.lang.Override
      public DevLogStartResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevLogStartResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevLogStartResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevLogStartResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogStartResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DevLogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevLogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 session_id = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required int32 session_id = 1;</code>
     */
    int getSessionId();

    /**
     * <code>required int32 sn = 2;</code>
     */
    boolean hasSn();
    /**
     * <code>required int32 sn = 2;</code>
     */
    int getSn();

    /**
     * <code>required bytes content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code DevLogData}
   */
  public  static final class DevLogData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevLogData)
      DevLogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevLogData.newBuilder() to construct.
    private DevLogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevLogData() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevLogData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sn_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <code>required int32 session_id = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 session_id = 1;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int SN_FIELD_NUMBER = 2;
    private int sn_;
    /**
     * <code>required int32 sn = 2;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sn = 2;</code>
     */
    public int getSn() {
      return sn_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData) obj;

      boolean result = true;
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasSn() == other.hasSn());
      if (hasSn()) {
        result = result && (getSn()
            == other.getSn());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId();
      }
      if (hasSn()) {
        hash = (37 * hash) + SN_FIELD_NUMBER;
        hash = (53 * hash) + getSn();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevLogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevLogData)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.internal_static_DevLogData_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.sessionId_ = sessionId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.sn_ = sn_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.content_ = content_;
          to_bitField0_ |= 0x00000004;
        } else {
          result.content_ = com.google.protobuf.ByteString.EMPTY;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        if (!hasSn()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sessionId_ ;
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int sn_ ;
      /**
       * <code>required int32 sn = 2;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sn = 2;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevLogData)
    }

    // @@protoc_insertion_point(class_scope:DevLogData)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevLogData>
        PARSER = new com.google.protobuf.AbstractParser<DevLogData>() {
      @java.lang.Override
      public DevLogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevLogData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevLogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevLogData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBDevLog.DevLogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevLogStartResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevLogStartResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevLogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevLogData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014DevLog.proto\"6\n\021DevLogStartResult\022\022\n\ns" +
      "ession_id\030\001 \002(\005\022\r\n\005total\030\002 \002(\005\"=\n\nDevLog" +
      "Data\022\022\n\nsession_id\030\001 \002(\005\022\n\n\002sn\030\002 \002(\005\022\017\n\007" +
      "content\030\003 \002(\014B3\n\'com.ryeex.groot.lib.ble" +
      ".stack.pb.entityB\010PBDevLog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DevLogStartResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DevLogStartResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevLogStartResult_descriptor,
        new java.lang.String[] { "SessionId", "Total", });
    internal_static_DevLogData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DevLogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevLogData_descriptor,
        new java.lang.String[] { "SessionId", "Sn", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
