// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DevStatistics.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBFDevStatistics {
  private PBFDevStatistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code STATISTICS_CMD}
   */
  public enum STATISTICS_CMD
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATISTICS_DEV_RESET_COUNT = 0;</code>
     */
    STATISTICS_DEV_RESET_COUNT(0),
    /**
     * <code>STATISTICS_DEV_WDT_COUNT = 1;</code>
     */
    STATISTICS_DEV_WDT_COUNT(1),
    /**
     * <code>STATISTICS_CHARGE_COUNT = 2;</code>
     */
    STATISTICS_CHARGE_COUNT(2),
    /**
     * <code>STATISTICS_HOME_COUNT = 3;</code>
     */
    STATISTICS_HOME_COUNT(3),
    /**
     * <code>STATISTICS_RAISE_WAKE_COUNT = 4;</code>
     */
    STATISTICS_RAISE_WAKE_COUNT(4),
    /**
     * <code>STATISTICS_MSG_COUNT = 5;</code>
     */
    STATISTICS_MSG_COUNT(5),
    /**
     * <code>STATISTICS_MSG_CLICK_COUNT = 6;</code>
     */
    STATISTICS_MSG_CLICK_COUNT(6),
    /**
     * <code>STATISTICS_DROP_COUNT = 7;</code>
     */
    STATISTICS_DROP_COUNT(7),
    /**
     * <code>STATISTICS_MENU_COUNT = 8;</code>
     */
    STATISTICS_MENU_COUNT(8),
    /**
     * <code>STATISTICS_HOME_BACK_COUNT = 9;</code>
     */
    STATISTICS_HOME_BACK_COUNT(9),
    /**
     * <code>STATISTICS_TRAFFIC_CARD_COUNT = 10;</code>
     */
    STATISTICS_TRAFFIC_CARD_COUNT(10),
    /**
     * <code>STATISTICS_DOOR_CARD_COUNT = 11;</code>
     */
    STATISTICS_DOOR_CARD_COUNT(11),
    /**
     * <code>STATISTICS_CARD_BAG_COUNT = 12;</code>
     */
    STATISTICS_CARD_BAG_COUNT(12),
    /**
     * <code>STATISTICS_CARD_CHANGE_COUNT = 13;</code>
     */
    STATISTICS_CARD_CHANGE_COUNT(13),
    /**
     * <code>STATISTICS_SPORT_COUNT = 14;</code>
     */
    STATISTICS_SPORT_COUNT(14),
    /**
     * <code>STATISTICS_SPORT_RASIE_COUNT = 15;</code>
     */
    STATISTICS_SPORT_RASIE_COUNT(15),
    /**
     * <code>STATISTICS_SPORT_CLICK_COUNT = 16;</code>
     */
    STATISTICS_SPORT_CLICK_COUNT(16),
    /**
     * <code>STATISTICS_SPORT_OUT_DOOR_RUN = 17;</code>
     */
    STATISTICS_SPORT_OUT_DOOR_RUN(17),
    /**
     * <code>STATISTICS_SPORT_PAUSE = 18;</code>
     */
    STATISTICS_SPORT_PAUSE(18),
    /**
     * <code>STATISTICS_SPORT_STOP = 19;</code>
     */
    STATISTICS_SPORT_STOP(19),
    /**
     * <code>STATISTICS_SPORT_FINISH = 20;</code>
     */
    STATISTICS_SPORT_FINISH(20),
    /**
     * <code>STATISTICS_HRM_COUNT = 21;</code>
     */
    STATISTICS_HRM_COUNT(21),
    /**
     * <code>STATISTICS_WEATHER_COUNT = 22;</code>
     */
    STATISTICS_WEATHER_COUNT(22),
    /**
     * <code>STATISTICS_WEATHER_CHANGE_COUNT = 23;</code>
     */
    STATISTICS_WEATHER_CHANGE_COUNT(23),
    /**
     * <code>STATISTICS_ALARM_COUNT = 24;</code>
     */
    STATISTICS_ALARM_COUNT(24),
    /**
     * <code>STATISTICS_ALARM_INFO_COUNT = 25;</code>
     */
    STATISTICS_ALARM_INFO_COUNT(25),
    /**
     * <code>STATISTICS_ALARM_OPEN_COUNT = 26;</code>
     */
    STATISTICS_ALARM_OPEN_COUNT(26),
    /**
     * <code>STATISTICS_ALARM_CLOSE_COUNT = 27;</code>
     */
    STATISTICS_ALARM_CLOSE_COUNT(27),
    /**
     * <code>STATISTICS_DATA_INFO_COUNT = 28;</code>
     */
    STATISTICS_DATA_INFO_COUNT(28),
    /**
     * <code>STATISTICS_MIJIA_COUNT = 29;</code>
     */
    STATISTICS_MIJIA_COUNT(29),
    /**
     * <code>STATISTICS_MIJIA_USE = 30;</code>
     */
    STATISTICS_MIJIA_USE(30),
    /**
     * <code>STATISTICS_SETTING_COUNT = 31;</code>
     */
    STATISTICS_SETTING_COUNT(31),
    /**
     * <code>STATISTICS_ABOUT_DEV_COUNT = 32;</code>
     */
    STATISTICS_ABOUT_DEV_COUNT(32),
    /**
     * <code>STATISTICS_FORBID_COUNT = 33;</code>
     */
    STATISTICS_FORBID_COUNT(33),
    /**
     * <code>STATISTICS_FORBID_OPEN_COUNT = 34;</code>
     */
    STATISTICS_FORBID_OPEN_COUNT(34),
    /**
     * <code>STATISTICS_FORBID_CLOSE_COUNT = 35;</code>
     */
    STATISTICS_FORBID_CLOSE_COUNT(35),
    /**
     * <code>STATISTICS_USER_RESET_COUNT = 36;</code>
     */
    STATISTICS_USER_RESET_COUNT(36),
    /**
     * <code>STATISTICS_USER_REPLACE_COUNT = 37;</code>
     */
    STATISTICS_USER_REPLACE_COUNT(37),
    /**
     * <code>STATISTICS_LAST_CHARGE_PRESENT = 38;</code>
     */
    STATISTICS_LAST_CHARGE_PRESENT(38),
    /**
     * <code>STATISTICS_LAST_CHARGE_TIME = 39;</code>
     */
    STATISTICS_LAST_CHARGE_TIME(39),
    /**
     * <code>STATISTICS_LAST_CHARGE_FULL_TIME = 40;</code>
     */
    STATISTICS_LAST_CHARGE_FULL_TIME(40),
    /**
     * <code>STATISTICS_LAST_CHARGE_NOT_FULL_TIME = 41;</code>
     */
    STATISTICS_LAST_CHARGE_NOT_FULL_TIME(41),
    /**
     * <code>STATISTICS_DROP_UP_COUNT = 42;</code>
     */
    STATISTICS_DROP_UP_COUNT(42),
    /**
     * <code>STATISTICS_DROP_DOWN_COUNT = 43;</code>
     */
    STATISTICS_DROP_DOWN_COUNT(43),
    /**
     * <code>STATISTICS_MENU_UP_COUNT = 44;</code>
     */
    STATISTICS_MENU_UP_COUNT(44),
    /**
     * <code>STATISTICS_MENU_DOWN_COUNT = 45;</code>
     */
    STATISTICS_MENU_DOWN_COUNT(45),
    ;

    /**
     * <code>STATISTICS_DEV_RESET_COUNT = 0;</code>
     */
    public static final int STATISTICS_DEV_RESET_COUNT_VALUE = 0;
    /**
     * <code>STATISTICS_DEV_WDT_COUNT = 1;</code>
     */
    public static final int STATISTICS_DEV_WDT_COUNT_VALUE = 1;
    /**
     * <code>STATISTICS_CHARGE_COUNT = 2;</code>
     */
    public static final int STATISTICS_CHARGE_COUNT_VALUE = 2;
    /**
     * <code>STATISTICS_HOME_COUNT = 3;</code>
     */
    public static final int STATISTICS_HOME_COUNT_VALUE = 3;
    /**
     * <code>STATISTICS_RAISE_WAKE_COUNT = 4;</code>
     */
    public static final int STATISTICS_RAISE_WAKE_COUNT_VALUE = 4;
    /**
     * <code>STATISTICS_MSG_COUNT = 5;</code>
     */
    public static final int STATISTICS_MSG_COUNT_VALUE = 5;
    /**
     * <code>STATISTICS_MSG_CLICK_COUNT = 6;</code>
     */
    public static final int STATISTICS_MSG_CLICK_COUNT_VALUE = 6;
    /**
     * <code>STATISTICS_DROP_COUNT = 7;</code>
     */
    public static final int STATISTICS_DROP_COUNT_VALUE = 7;
    /**
     * <code>STATISTICS_MENU_COUNT = 8;</code>
     */
    public static final int STATISTICS_MENU_COUNT_VALUE = 8;
    /**
     * <code>STATISTICS_HOME_BACK_COUNT = 9;</code>
     */
    public static final int STATISTICS_HOME_BACK_COUNT_VALUE = 9;
    /**
     * <code>STATISTICS_TRAFFIC_CARD_COUNT = 10;</code>
     */
    public static final int STATISTICS_TRAFFIC_CARD_COUNT_VALUE = 10;
    /**
     * <code>STATISTICS_DOOR_CARD_COUNT = 11;</code>
     */
    public static final int STATISTICS_DOOR_CARD_COUNT_VALUE = 11;
    /**
     * <code>STATISTICS_CARD_BAG_COUNT = 12;</code>
     */
    public static final int STATISTICS_CARD_BAG_COUNT_VALUE = 12;
    /**
     * <code>STATISTICS_CARD_CHANGE_COUNT = 13;</code>
     */
    public static final int STATISTICS_CARD_CHANGE_COUNT_VALUE = 13;
    /**
     * <code>STATISTICS_SPORT_COUNT = 14;</code>
     */
    public static final int STATISTICS_SPORT_COUNT_VALUE = 14;
    /**
     * <code>STATISTICS_SPORT_RASIE_COUNT = 15;</code>
     */
    public static final int STATISTICS_SPORT_RASIE_COUNT_VALUE = 15;
    /**
     * <code>STATISTICS_SPORT_CLICK_COUNT = 16;</code>
     */
    public static final int STATISTICS_SPORT_CLICK_COUNT_VALUE = 16;
    /**
     * <code>STATISTICS_SPORT_OUT_DOOR_RUN = 17;</code>
     */
    public static final int STATISTICS_SPORT_OUT_DOOR_RUN_VALUE = 17;
    /**
     * <code>STATISTICS_SPORT_PAUSE = 18;</code>
     */
    public static final int STATISTICS_SPORT_PAUSE_VALUE = 18;
    /**
     * <code>STATISTICS_SPORT_STOP = 19;</code>
     */
    public static final int STATISTICS_SPORT_STOP_VALUE = 19;
    /**
     * <code>STATISTICS_SPORT_FINISH = 20;</code>
     */
    public static final int STATISTICS_SPORT_FINISH_VALUE = 20;
    /**
     * <code>STATISTICS_HRM_COUNT = 21;</code>
     */
    public static final int STATISTICS_HRM_COUNT_VALUE = 21;
    /**
     * <code>STATISTICS_WEATHER_COUNT = 22;</code>
     */
    public static final int STATISTICS_WEATHER_COUNT_VALUE = 22;
    /**
     * <code>STATISTICS_WEATHER_CHANGE_COUNT = 23;</code>
     */
    public static final int STATISTICS_WEATHER_CHANGE_COUNT_VALUE = 23;
    /**
     * <code>STATISTICS_ALARM_COUNT = 24;</code>
     */
    public static final int STATISTICS_ALARM_COUNT_VALUE = 24;
    /**
     * <code>STATISTICS_ALARM_INFO_COUNT = 25;</code>
     */
    public static final int STATISTICS_ALARM_INFO_COUNT_VALUE = 25;
    /**
     * <code>STATISTICS_ALARM_OPEN_COUNT = 26;</code>
     */
    public static final int STATISTICS_ALARM_OPEN_COUNT_VALUE = 26;
    /**
     * <code>STATISTICS_ALARM_CLOSE_COUNT = 27;</code>
     */
    public static final int STATISTICS_ALARM_CLOSE_COUNT_VALUE = 27;
    /**
     * <code>STATISTICS_DATA_INFO_COUNT = 28;</code>
     */
    public static final int STATISTICS_DATA_INFO_COUNT_VALUE = 28;
    /**
     * <code>STATISTICS_MIJIA_COUNT = 29;</code>
     */
    public static final int STATISTICS_MIJIA_COUNT_VALUE = 29;
    /**
     * <code>STATISTICS_MIJIA_USE = 30;</code>
     */
    public static final int STATISTICS_MIJIA_USE_VALUE = 30;
    /**
     * <code>STATISTICS_SETTING_COUNT = 31;</code>
     */
    public static final int STATISTICS_SETTING_COUNT_VALUE = 31;
    /**
     * <code>STATISTICS_ABOUT_DEV_COUNT = 32;</code>
     */
    public static final int STATISTICS_ABOUT_DEV_COUNT_VALUE = 32;
    /**
     * <code>STATISTICS_FORBID_COUNT = 33;</code>
     */
    public static final int STATISTICS_FORBID_COUNT_VALUE = 33;
    /**
     * <code>STATISTICS_FORBID_OPEN_COUNT = 34;</code>
     */
    public static final int STATISTICS_FORBID_OPEN_COUNT_VALUE = 34;
    /**
     * <code>STATISTICS_FORBID_CLOSE_COUNT = 35;</code>
     */
    public static final int STATISTICS_FORBID_CLOSE_COUNT_VALUE = 35;
    /**
     * <code>STATISTICS_USER_RESET_COUNT = 36;</code>
     */
    public static final int STATISTICS_USER_RESET_COUNT_VALUE = 36;
    /**
     * <code>STATISTICS_USER_REPLACE_COUNT = 37;</code>
     */
    public static final int STATISTICS_USER_REPLACE_COUNT_VALUE = 37;
    /**
     * <code>STATISTICS_LAST_CHARGE_PRESENT = 38;</code>
     */
    public static final int STATISTICS_LAST_CHARGE_PRESENT_VALUE = 38;
    /**
     * <code>STATISTICS_LAST_CHARGE_TIME = 39;</code>
     */
    public static final int STATISTICS_LAST_CHARGE_TIME_VALUE = 39;
    /**
     * <code>STATISTICS_LAST_CHARGE_FULL_TIME = 40;</code>
     */
    public static final int STATISTICS_LAST_CHARGE_FULL_TIME_VALUE = 40;
    /**
     * <code>STATISTICS_LAST_CHARGE_NOT_FULL_TIME = 41;</code>
     */
    public static final int STATISTICS_LAST_CHARGE_NOT_FULL_TIME_VALUE = 41;
    /**
     * <code>STATISTICS_DROP_UP_COUNT = 42;</code>
     */
    public static final int STATISTICS_DROP_UP_COUNT_VALUE = 42;
    /**
     * <code>STATISTICS_DROP_DOWN_COUNT = 43;</code>
     */
    public static final int STATISTICS_DROP_DOWN_COUNT_VALUE = 43;
    /**
     * <code>STATISTICS_MENU_UP_COUNT = 44;</code>
     */
    public static final int STATISTICS_MENU_UP_COUNT_VALUE = 44;
    /**
     * <code>STATISTICS_MENU_DOWN_COUNT = 45;</code>
     */
    public static final int STATISTICS_MENU_DOWN_COUNT_VALUE = 45;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static STATISTICS_CMD valueOf(int value) {
      return forNumber(value);
    }

    public static STATISTICS_CMD forNumber(int value) {
      switch (value) {
        case 0: return STATISTICS_DEV_RESET_COUNT;
        case 1: return STATISTICS_DEV_WDT_COUNT;
        case 2: return STATISTICS_CHARGE_COUNT;
        case 3: return STATISTICS_HOME_COUNT;
        case 4: return STATISTICS_RAISE_WAKE_COUNT;
        case 5: return STATISTICS_MSG_COUNT;
        case 6: return STATISTICS_MSG_CLICK_COUNT;
        case 7: return STATISTICS_DROP_COUNT;
        case 8: return STATISTICS_MENU_COUNT;
        case 9: return STATISTICS_HOME_BACK_COUNT;
        case 10: return STATISTICS_TRAFFIC_CARD_COUNT;
        case 11: return STATISTICS_DOOR_CARD_COUNT;
        case 12: return STATISTICS_CARD_BAG_COUNT;
        case 13: return STATISTICS_CARD_CHANGE_COUNT;
        case 14: return STATISTICS_SPORT_COUNT;
        case 15: return STATISTICS_SPORT_RASIE_COUNT;
        case 16: return STATISTICS_SPORT_CLICK_COUNT;
        case 17: return STATISTICS_SPORT_OUT_DOOR_RUN;
        case 18: return STATISTICS_SPORT_PAUSE;
        case 19: return STATISTICS_SPORT_STOP;
        case 20: return STATISTICS_SPORT_FINISH;
        case 21: return STATISTICS_HRM_COUNT;
        case 22: return STATISTICS_WEATHER_COUNT;
        case 23: return STATISTICS_WEATHER_CHANGE_COUNT;
        case 24: return STATISTICS_ALARM_COUNT;
        case 25: return STATISTICS_ALARM_INFO_COUNT;
        case 26: return STATISTICS_ALARM_OPEN_COUNT;
        case 27: return STATISTICS_ALARM_CLOSE_COUNT;
        case 28: return STATISTICS_DATA_INFO_COUNT;
        case 29: return STATISTICS_MIJIA_COUNT;
        case 30: return STATISTICS_MIJIA_USE;
        case 31: return STATISTICS_SETTING_COUNT;
        case 32: return STATISTICS_ABOUT_DEV_COUNT;
        case 33: return STATISTICS_FORBID_COUNT;
        case 34: return STATISTICS_FORBID_OPEN_COUNT;
        case 35: return STATISTICS_FORBID_CLOSE_COUNT;
        case 36: return STATISTICS_USER_RESET_COUNT;
        case 37: return STATISTICS_USER_REPLACE_COUNT;
        case 38: return STATISTICS_LAST_CHARGE_PRESENT;
        case 39: return STATISTICS_LAST_CHARGE_TIME;
        case 40: return STATISTICS_LAST_CHARGE_FULL_TIME;
        case 41: return STATISTICS_LAST_CHARGE_NOT_FULL_TIME;
        case 42: return STATISTICS_DROP_UP_COUNT;
        case 43: return STATISTICS_DROP_DOWN_COUNT;
        case 44: return STATISTICS_MENU_UP_COUNT;
        case 45: return STATISTICS_MENU_DOWN_COUNT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<STATISTICS_CMD>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        STATISTICS_CMD> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<STATISTICS_CMD>() {
            public STATISTICS_CMD findValueByNumber(int number) {
              return STATISTICS_CMD.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.getDescriptor().getEnumTypes().get(0);
    }

    private static final STATISTICS_CMD[] VALUES = values();

    public static STATISTICS_CMD valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private STATISTICS_CMD(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:STATISTICS_CMD)
  }

  public interface DevStatisticsResultRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevStatisticsResultRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .STATISTICS_CMD type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .STATISTICS_CMD type = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD getType();

    /**
     * <code>required int32 val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>required int32 val = 2;</code>
     */
    int getVal();
  }
  /**
   * Protobuf type {@code DevStatisticsResultRecord}
   */
  public  static final class DevStatisticsResultRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevStatisticsResultRecord)
      DevStatisticsResultRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevStatisticsResultRecord.newBuilder() to construct.
    private DevStatisticsResultRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevStatisticsResultRecord() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevStatisticsResultRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD value = com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              val_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResultRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResultRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .STATISTICS_CMD type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .STATISTICS_CMD type = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD getType() {
      @SuppressWarnings("deprecation")
      com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD result = com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD.valueOf(type_);
      return result == null ? com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD.STATISTICS_DEV_RESET_COUNT : result;
    }

    public static final int VAL_FIELD_NUMBER = 2;
    private int val_;
    /**
     * <code>required int32 val = 2;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 val = 2;</code>
     */
    public int getVal() {
      return val_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, val_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, val_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasVal() == other.hasVal());
      if (hasVal()) {
        result = result && (getVal()
            == other.getVal());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasVal()) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevStatisticsResultRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevStatisticsResultRecord)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResultRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResultRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResultRecord_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.type_ = 0;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.val_ = val_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasVal()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .STATISTICS_CMD type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .STATISTICS_CMD type = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD getType() {
        @SuppressWarnings("deprecation")
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD result = com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD.valueOf(type_);
        return result == null ? com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD.STATISTICS_DEV_RESET_COUNT : result;
      }
      /**
       * <code>required .STATISTICS_CMD type = 1;</code>
       */
      public Builder setType(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.STATISTICS_CMD value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .STATISTICS_CMD type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int val_ ;
      /**
       * <code>required int32 val = 2;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public int getVal() {
        return val_;
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public Builder setVal(int value) {
        bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevStatisticsResultRecord)
    }

    // @@protoc_insertion_point(class_scope:DevStatisticsResultRecord)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevStatisticsResultRecord>
        PARSER = new com.google.protobuf.AbstractParser<DevStatisticsResultRecord>() {
      @java.lang.Override
      public DevStatisticsResultRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevStatisticsResultRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevStatisticsResultRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevStatisticsResultRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DevStatisticsResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DevStatisticsResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> 
        getRecordsList();
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getRecords(int index);
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    int getRecordsCount();
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder> 
        getRecordsOrBuilderList();
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder getRecordsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DevStatisticsResult}
   */
  public  static final class DevStatisticsResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DevStatisticsResult)
      DevStatisticsResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DevStatisticsResult.newBuilder() to construct.
    private DevStatisticsResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DevStatisticsResult() {
      records_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DevStatisticsResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                records_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              records_.add(
                  input.readMessage(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          records_ = java.util.Collections.unmodifiableList(records_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.Builder.class);
    }

    public static final int RECORDS_FIELD_NUMBER = 1;
    private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> records_;
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> getRecordsList() {
      return records_;
    }
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder> 
        getRecordsOrBuilderList() {
      return records_;
    }
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    public int getRecordsCount() {
      return records_.size();
    }
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getRecords(int index) {
      return records_.get(index);
    }
    /**
     * <code>repeated .DevStatisticsResultRecord records = 1;</code>
     */
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder getRecordsOrBuilder(
        int index) {
      return records_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRecordsCount(); i++) {
        if (!getRecords(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < records_.size(); i++) {
        output.writeMessage(1, records_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < records_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, records_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult) obj;

      boolean result = true;
      result = result && getRecordsList()
          .equals(other.getRecordsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecordsCount() > 0) {
        hash = (37 * hash) + RECORDS_FIELD_NUMBER;
        hash = (53 * hash) + getRecordsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DevStatisticsResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DevStatisticsResult)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.internal_static_DevStatisticsResult_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult(this);
        int from_bitField0_ = bitField0_;
        if (recordsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            records_ = java.util.Collections.unmodifiableList(records_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.records_ = records_;
        } else {
          result.records_ = recordsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult.getDefaultInstance()) return this;
        if (recordsBuilder_ == null) {
          if (!other.records_.isEmpty()) {
            if (records_.isEmpty()) {
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordsIsMutable();
              records_.addAll(other.records_);
            }
            onChanged();
          }
        } else {
          if (!other.records_.isEmpty()) {
            if (recordsBuilder_.isEmpty()) {
              recordsBuilder_.dispose();
              recordsBuilder_ = null;
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordsFieldBuilder() : null;
            } else {
              recordsBuilder_.addAllMessages(other.records_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getRecordsCount(); i++) {
          if (!getRecords(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> records_ =
        java.util.Collections.emptyList();
      private void ensureRecordsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          records_ = new java.util.ArrayList<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord>(records_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder> recordsBuilder_;

      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> getRecordsList() {
        if (recordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(records_);
        } else {
          return recordsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public int getRecordsCount() {
        if (recordsBuilder_ == null) {
          return records_.size();
        } else {
          return recordsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord getRecords(int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);
        } else {
          return recordsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder setRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.set(index, value);
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder setRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder addRecords(com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder addRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(index, value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder addRecords(
          com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder addRecords(
          int index, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder addAllRecords(
          java.lang.Iterable<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord> values) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, records_);
          onChanged();
        } else {
          recordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder clearRecords() {
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public Builder removeRecords(int index) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.remove(index);
          onChanged();
        } else {
          recordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder getRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder getRecordsOrBuilder(
          int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);  } else {
          return recordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public java.util.List<? extends com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder> 
           getRecordsOrBuilderList() {
        if (recordsBuilder_ != null) {
          return recordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(records_);
        }
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder addRecordsBuilder() {
        return getRecordsFieldBuilder().addBuilder(
            com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder addRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().addBuilder(
            index, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .DevStatisticsResultRecord records = 1;</code>
       */
      public java.util.List<com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder> 
           getRecordsBuilderList() {
        return getRecordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder> 
          getRecordsFieldBuilder() {
        if (recordsBuilder_ == null) {
          recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecord.Builder, com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResultRecordOrBuilder>(
                  records_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          records_ = null;
        }
        return recordsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DevStatisticsResult)
    }

    // @@protoc_insertion_point(class_scope:DevStatisticsResult)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DevStatisticsResult>
        PARSER = new com.google.protobuf.AbstractParser<DevStatisticsResult>() {
      @java.lang.Override
      public DevStatisticsResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DevStatisticsResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DevStatisticsResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DevStatisticsResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBFDevStatistics.DevStatisticsResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevStatisticsResultRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevStatisticsResultRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DevStatisticsResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DevStatisticsResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DevStatistics.proto\"G\n\031DevStatisticsRe" +
      "sultRecord\022\035\n\004type\030\001 \002(\0162\017.STATISTICS_CM" +
      "D\022\013\n\003val\030\002 \002(\005\"B\n\023DevStatisticsResult\022+\n" +
      "\007records\030\001 \003(\0132\032.DevStatisticsResultReco" +
      "rd*\272\013\n\016STATISTICS_CMD\022\036\n\032STATISTICS_DEV_" +
      "RESET_COUNT\020\000\022\034\n\030STATISTICS_DEV_WDT_COUN" +
      "T\020\001\022\033\n\027STATISTICS_CHARGE_COUNT\020\002\022\031\n\025STAT" +
      "ISTICS_HOME_COUNT\020\003\022\037\n\033STATISTICS_RAISE_" +
      "WAKE_COUNT\020\004\022\030\n\024STATISTICS_MSG_COUNT\020\005\022\036" +
      "\n\032STATISTICS_MSG_CLICK_COUNT\020\006\022\031\n\025STATIS" +
      "TICS_DROP_COUNT\020\007\022\031\n\025STATISTICS_MENU_COU" +
      "NT\020\010\022\036\n\032STATISTICS_HOME_BACK_COUNT\020\t\022!\n\035" +
      "STATISTICS_TRAFFIC_CARD_COUNT\020\n\022\036\n\032STATI" +
      "STICS_DOOR_CARD_COUNT\020\013\022\035\n\031STATISTICS_CA" +
      "RD_BAG_COUNT\020\014\022 \n\034STATISTICS_CARD_CHANGE" +
      "_COUNT\020\r\022\032\n\026STATISTICS_SPORT_COUNT\020\016\022 \n\034" +
      "STATISTICS_SPORT_RASIE_COUNT\020\017\022 \n\034STATIS" +
      "TICS_SPORT_CLICK_COUNT\020\020\022!\n\035STATISTICS_S" +
      "PORT_OUT_DOOR_RUN\020\021\022\032\n\026STATISTICS_SPORT_" +
      "PAUSE\020\022\022\031\n\025STATISTICS_SPORT_STOP\020\023\022\033\n\027ST" +
      "ATISTICS_SPORT_FINISH\020\024\022\030\n\024STATISTICS_HR" +
      "M_COUNT\020\025\022\034\n\030STATISTICS_WEATHER_COUNT\020\026\022" +
      "#\n\037STATISTICS_WEATHER_CHANGE_COUNT\020\027\022\032\n\026" +
      "STATISTICS_ALARM_COUNT\020\030\022\037\n\033STATISTICS_A" +
      "LARM_INFO_COUNT\020\031\022\037\n\033STATISTICS_ALARM_OP" +
      "EN_COUNT\020\032\022 \n\034STATISTICS_ALARM_CLOSE_COU" +
      "NT\020\033\022\036\n\032STATISTICS_DATA_INFO_COUNT\020\034\022\032\n\026" +
      "STATISTICS_MIJIA_COUNT\020\035\022\030\n\024STATISTICS_M" +
      "IJIA_USE\020\036\022\034\n\030STATISTICS_SETTING_COUNT\020\037" +
      "\022\036\n\032STATISTICS_ABOUT_DEV_COUNT\020 \022\033\n\027STAT" +
      "ISTICS_FORBID_COUNT\020!\022 \n\034STATISTICS_FORB" +
      "ID_OPEN_COUNT\020\"\022!\n\035STATISTICS_FORBID_CLO" +
      "SE_COUNT\020#\022\037\n\033STATISTICS_USER_RESET_COUN" +
      "T\020$\022!\n\035STATISTICS_USER_REPLACE_COUNT\020%\022\"" +
      "\n\036STATISTICS_LAST_CHARGE_PRESENT\020&\022\037\n\033ST" +
      "ATISTICS_LAST_CHARGE_TIME\020\'\022$\n STATISTIC" +
      "S_LAST_CHARGE_FULL_TIME\020(\022(\n$STATISTICS_" +
      "LAST_CHARGE_NOT_FULL_TIME\020)\022\034\n\030STATISTIC" +
      "S_DROP_UP_COUNT\020*\022\036\n\032STATISTICS_DROP_DOW" +
      "N_COUNT\020+\022\034\n\030STATISTICS_MENU_UP_COUNT\020,\022" +
      "\036\n\032STATISTICS_MENU_DOWN_COUNT\020-B;\n\'com.r" +
      "yeex.groot.lib.ble.stack.pb.entityB\020PBFD" +
      "evStatistics"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DevStatisticsResultRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DevStatisticsResultRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevStatisticsResultRecord_descriptor,
        new java.lang.String[] { "Type", "Val", });
    internal_static_DevStatisticsResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DevStatisticsResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DevStatisticsResult_descriptor,
        new java.lang.String[] { "Records", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
