// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBLocation {
  private PBLocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    int getSessionId();

    /**
     * <pre>
     *上次的经度
     * </pre>
     *
     * <code>optional double last_longitude = 2;</code>
     */
    boolean hasLastLongitude();
    /**
     * <pre>
     *上次的经度
     * </pre>
     *
     * <code>optional double last_longitude = 2;</code>
     */
    double getLastLongitude();

    /**
     * <pre>
     *上次的纬度
     * </pre>
     *
     * <code>optional double last_latitude = 3;</code>
     */
    boolean hasLastLatitude();
    /**
     * <pre>
     *上次的纬度
     * </pre>
     *
     * <code>optional double last_latitude = 3;</code>
     */
    double getLastLatitude();
  }
  /**
   * Protobuf type {@code LocationRequest}
   */
  public  static final class LocationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationRequest)
      LocationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationRequest.newBuilder() to construct.
    private LocationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lastLongitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lastLatitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int LAST_LONGITUDE_FIELD_NUMBER = 2;
    private double lastLongitude_;
    /**
     * <pre>
     *上次的经度
     * </pre>
     *
     * <code>optional double last_longitude = 2;</code>
     */
    public boolean hasLastLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *上次的经度
     * </pre>
     *
     * <code>optional double last_longitude = 2;</code>
     */
    public double getLastLongitude() {
      return lastLongitude_;
    }

    public static final int LAST_LATITUDE_FIELD_NUMBER = 3;
    private double lastLatitude_;
    /**
     * <pre>
     *上次的纬度
     * </pre>
     *
     * <code>optional double last_latitude = 3;</code>
     */
    public boolean hasLastLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *上次的纬度
     * </pre>
     *
     * <code>optional double last_latitude = 3;</code>
     */
    public double getLastLatitude() {
      return lastLatitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lastLongitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lastLatitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lastLongitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lastLatitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest) obj;

      boolean result = true;
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasLastLongitude() == other.hasLastLongitude());
      if (hasLastLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLastLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLastLongitude()));
      }
      result = result && (hasLastLatitude() == other.hasLastLatitude());
      if (hasLastLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLastLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLastLatitude()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId();
      }
      if (hasLastLongitude()) {
        hash = (37 * hash) + LAST_LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLastLongitude()));
      }
      if (hasLastLatitude()) {
        hash = (37 * hash) + LAST_LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLastLatitude()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationRequest)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lastLongitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastLatitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationRequest_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.sessionId_ = sessionId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.lastLongitude_ = lastLongitude_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.lastLatitude_ = lastLatitude_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasLastLongitude()) {
          setLastLongitude(other.getLastLongitude());
        }
        if (other.hasLastLatitude()) {
          setLastLatitude(other.getLastLatitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sessionId_ ;
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private double lastLongitude_ ;
      /**
       * <pre>
       *上次的经度
       * </pre>
       *
       * <code>optional double last_longitude = 2;</code>
       */
      public boolean hasLastLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *上次的经度
       * </pre>
       *
       * <code>optional double last_longitude = 2;</code>
       */
      public double getLastLongitude() {
        return lastLongitude_;
      }
      /**
       * <pre>
       *上次的经度
       * </pre>
       *
       * <code>optional double last_longitude = 2;</code>
       */
      public Builder setLastLongitude(double value) {
        bitField0_ |= 0x00000002;
        lastLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *上次的经度
       * </pre>
       *
       * <code>optional double last_longitude = 2;</code>
       */
      public Builder clearLastLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastLongitude_ = 0D;
        onChanged();
        return this;
      }

      private double lastLatitude_ ;
      /**
       * <pre>
       *上次的纬度
       * </pre>
       *
       * <code>optional double last_latitude = 3;</code>
       */
      public boolean hasLastLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *上次的纬度
       * </pre>
       *
       * <code>optional double last_latitude = 3;</code>
       */
      public double getLastLatitude() {
        return lastLatitude_;
      }
      /**
       * <pre>
       *上次的纬度
       * </pre>
       *
       * <code>optional double last_latitude = 3;</code>
       */
      public Builder setLastLatitude(double value) {
        bitField0_ |= 0x00000004;
        lastLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *上次的纬度
       * </pre>
       *
       * <code>optional double last_latitude = 3;</code>
       */
      public Builder clearLastLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLatitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocationRequest)
    }

    // @@protoc_insertion_point(class_scope:LocationRequest)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LocationRequest>
        PARSER = new com.google.protobuf.AbstractParser<LocationRequest>() {
      @java.lang.Override
      public LocationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LocationResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    int getSessionId();

    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();

    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>required double latitude = 3;</code>
     */
    boolean hasLatitude();
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>required double latitude = 3;</code>
     */
    double getLatitude();

    /**
     * <pre>
     *当前坐标与上次坐标的距离
     * </pre>
     *
     * <code>optional float last_distance = 4;</code>
     */
    boolean hasLastDistance();
    /**
     * <pre>
     *当前坐标与上次坐标的距离
     * </pre>
     *
     * <code>optional float last_distance = 4;</code>
     */
    float getLastDistance();
  }
  /**
   * Protobuf type {@code LocationResult}
   */
  public  static final class LocationResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LocationResult)
      LocationResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationResult.newBuilder() to construct.
    private LocationResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationResult() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              latitude_ = input.readDouble();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              lastDistance_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.Builder.class);
    }

    private int bitField0_;
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private int sessionId_;
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *异步接口的会话id
     * </pre>
     *
     * <code>required int32 session_id = 1;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *经度
     * </pre>
     *
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>required double latitude = 3;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *纬度
     * </pre>
     *
     * <code>required double latitude = 3;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LAST_DISTANCE_FIELD_NUMBER = 4;
    private float lastDistance_;
    /**
     * <pre>
     *当前坐标与上次坐标的距离
     * </pre>
     *
     * <code>optional float last_distance = 4;</code>
     */
    public boolean hasLastDistance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *当前坐标与上次坐标的距离
     * </pre>
     *
     * <code>optional float last_distance = 4;</code>
     */
    public float getLastDistance() {
      return lastDistance_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, lastDistance_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, lastDistance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult) obj;

      boolean result = true;
      result = result && (hasSessionId() == other.hasSessionId());
      if (hasSessionId()) {
        result = result && (getSessionId()
            == other.getSessionId());
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLastDistance() == other.hasLastDistance());
      if (hasLastDistance()) {
        result = result && (
            java.lang.Float.floatToIntBits(getLastDistance())
            == java.lang.Float.floatToIntBits(
                other.getLastDistance()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId();
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLastDistance()) {
        hash = (37 * hash) + LAST_DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLastDistance());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LocationResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LocationResult)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastDistance_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.internal_static_LocationResult_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.sessionId_ = sessionId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.latitude_ = latitude_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          result.lastDistance_ = lastDistance_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLastDistance()) {
          setLastDistance(other.getLastDistance());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSessionId()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasLatitude()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sessionId_ ;
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异步接口的会话id
       * </pre>
       *
       * <code>required int32 session_id = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *经度
       * </pre>
       *
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>required double latitude = 3;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>required double latitude = 3;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>required double latitude = 3;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000004;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *纬度
       * </pre>
       *
       * <code>required double latitude = 3;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private float lastDistance_ ;
      /**
       * <pre>
       *当前坐标与上次坐标的距离
       * </pre>
       *
       * <code>optional float last_distance = 4;</code>
       */
      public boolean hasLastDistance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *当前坐标与上次坐标的距离
       * </pre>
       *
       * <code>optional float last_distance = 4;</code>
       */
      public float getLastDistance() {
        return lastDistance_;
      }
      /**
       * <pre>
       *当前坐标与上次坐标的距离
       * </pre>
       *
       * <code>optional float last_distance = 4;</code>
       */
      public Builder setLastDistance(float value) {
        bitField0_ |= 0x00000008;
        lastDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前坐标与上次坐标的距离
       * </pre>
       *
       * <code>optional float last_distance = 4;</code>
       */
      public Builder clearLastDistance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastDistance_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LocationResult)
    }

    // @@protoc_insertion_point(class_scope:LocationResult)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LocationResult>
        PARSER = new com.google.protobuf.AbstractParser<LocationResult>() {
      @java.lang.Override
      public LocationResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocationResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBLocation.LocationResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Location.proto\"T\n\017LocationRequest\022\022\n\ns" +
      "ession_id\030\001 \002(\005\022\026\n\016last_longitude\030\002 \001(\001\022" +
      "\025\n\rlast_latitude\030\003 \001(\001\"`\n\016LocationResult" +
      "\022\022\n\nsession_id\030\001 \002(\005\022\021\n\tlongitude\030\002 \002(\001\022" +
      "\020\n\010latitude\030\003 \002(\001\022\025\n\rlast_distance\030\004 \001(\002" +
      "B5\n\'com.ryeex.groot.lib.ble.stack.pb.ent" +
      "ityB\nPBLocation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationRequest_descriptor,
        new java.lang.String[] { "SessionId", "LastLongitude", "LastLatitude", });
    internal_static_LocationResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LocationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationResult_descriptor,
        new java.lang.String[] { "SessionId", "Longitude", "Latitude", "LastDistance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
