// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RbpResCode.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBRbpResCode {
  private PBRbpResCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RbpResCode}
   */
  public enum RbpResCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>LOW_POWER = 1;</code>
     */
    LOW_POWER(1),
    /**
     * <code>DECODE_FAIL = 2;</code>
     */
    DECODE_FAIL(2),
    /**
     * <code>NOT_FOUND = 3;</code>
     */
    NOT_FOUND(3),
    /**
     * <code>INVALID_PARA = 4;</code>
     */
    INVALID_PARA(4),
    /**
     * <code>NO_MEM = 5;</code>
     */
    NO_MEM(5),
    /**
     * <code>EXE_FAIL = 6;</code>
     */
    EXE_FAIL(6),
    /**
     * <code>TBL_FULL = 7;</code>
     */
    TBL_FULL(7),
    /**
     * <code>ENCODE_FAIL = 8;</code>
     */
    ENCODE_FAIL(8),
    /**
     * <code>SIGN_VERIFY_FAIL = 9;</code>
     */
    SIGN_VERIFY_FAIL(9),
    /**
     * <code>NO_BIND = 10;</code>
     */
    NO_BIND(10),
    /**
     * <code>ALREADY_EXIST = 11;</code>
     */
    ALREADY_EXIST(11),
    /**
     * <code>INVALID_STATE = 12;</code>
     */
    INVALID_STATE(12),
    /**
     * <code>INVALID_STATE_RUNNING = 13;</code>
     */
    INVALID_STATE_RUNNING(13),
    /**
     * <code>INVALID_STATE_OTA = 14;</code>
     */
    INVALID_STATE_OTA(14),
    /**
     * <code>INVALID_STATE_CARD = 15;</code>
     */
    INVALID_STATE_CARD(15),
    /**
     * <code>INVALID_STATE_UPLOAD_DATA = 16;</code>
     */
    INVALID_STATE_UPLOAD_DATA(16),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>LOW_POWER = 1;</code>
     */
    public static final int LOW_POWER_VALUE = 1;
    /**
     * <code>DECODE_FAIL = 2;</code>
     */
    public static final int DECODE_FAIL_VALUE = 2;
    /**
     * <code>NOT_FOUND = 3;</code>
     */
    public static final int NOT_FOUND_VALUE = 3;
    /**
     * <code>INVALID_PARA = 4;</code>
     */
    public static final int INVALID_PARA_VALUE = 4;
    /**
     * <code>NO_MEM = 5;</code>
     */
    public static final int NO_MEM_VALUE = 5;
    /**
     * <code>EXE_FAIL = 6;</code>
     */
    public static final int EXE_FAIL_VALUE = 6;
    /**
     * <code>TBL_FULL = 7;</code>
     */
    public static final int TBL_FULL_VALUE = 7;
    /**
     * <code>ENCODE_FAIL = 8;</code>
     */
    public static final int ENCODE_FAIL_VALUE = 8;
    /**
     * <code>SIGN_VERIFY_FAIL = 9;</code>
     */
    public static final int SIGN_VERIFY_FAIL_VALUE = 9;
    /**
     * <code>NO_BIND = 10;</code>
     */
    public static final int NO_BIND_VALUE = 10;
    /**
     * <code>ALREADY_EXIST = 11;</code>
     */
    public static final int ALREADY_EXIST_VALUE = 11;
    /**
     * <code>INVALID_STATE = 12;</code>
     */
    public static final int INVALID_STATE_VALUE = 12;
    /**
     * <code>INVALID_STATE_RUNNING = 13;</code>
     */
    public static final int INVALID_STATE_RUNNING_VALUE = 13;
    /**
     * <code>INVALID_STATE_OTA = 14;</code>
     */
    public static final int INVALID_STATE_OTA_VALUE = 14;
    /**
     * <code>INVALID_STATE_CARD = 15;</code>
     */
    public static final int INVALID_STATE_CARD_VALUE = 15;
    /**
     * <code>INVALID_STATE_UPLOAD_DATA = 16;</code>
     */
    public static final int INVALID_STATE_UPLOAD_DATA_VALUE = 16;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RbpResCode valueOf(int value) {
      return forNumber(value);
    }

    public static RbpResCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return LOW_POWER;
        case 2: return DECODE_FAIL;
        case 3: return NOT_FOUND;
        case 4: return INVALID_PARA;
        case 5: return NO_MEM;
        case 6: return EXE_FAIL;
        case 7: return TBL_FULL;
        case 8: return ENCODE_FAIL;
        case 9: return SIGN_VERIFY_FAIL;
        case 10: return NO_BIND;
        case 11: return ALREADY_EXIST;
        case 12: return INVALID_STATE;
        case 13: return INVALID_STATE_RUNNING;
        case 14: return INVALID_STATE_OTA;
        case 15: return INVALID_STATE_CARD;
        case 16: return INVALID_STATE_UPLOAD_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RbpResCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RbpResCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RbpResCode>() {
            public RbpResCode findValueByNumber(int number) {
              return RbpResCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBRbpResCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final RbpResCode[] VALUES = values();

    public static RbpResCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RbpResCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RbpResCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RbpResCode.proto*\305\002\n\nRbpResCode\022\013\n\007SUC" +
      "CESS\020\000\022\r\n\tLOW_POWER\020\001\022\017\n\013DECODE_FAIL\020\002\022\r" +
      "\n\tNOT_FOUND\020\003\022\020\n\014INVALID_PARA\020\004\022\n\n\006NO_ME" +
      "M\020\005\022\014\n\010EXE_FAIL\020\006\022\014\n\010TBL_FULL\020\007\022\017\n\013ENCOD" +
      "E_FAIL\020\010\022\024\n\020SIGN_VERIFY_FAIL\020\t\022\013\n\007NO_BIN" +
      "D\020\n\022\021\n\rALREADY_EXIST\020\013\022\021\n\rINVALID_STATE\020" +
      "\014\022\031\n\025INVALID_STATE_RUNNING\020\r\022\025\n\021INVALID_" +
      "STATE_OTA\020\016\022\026\n\022INVALID_STATE_CARD\020\017\022\035\n\031I" +
      "NVALID_STATE_UPLOAD_DATA\020\020B7\n\'com.ryeex." +
      "groot.lib.ble.stack.pb.entityB\014PBRbpResC" +
      "ode"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
