// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transit.proto

package com.ryeex.groot.lib.ble.stack.pb.entity;

public final class PBTransit {
  private PBTransit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransitCreateParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransitCreateParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    boolean hasAid();
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    com.google.protobuf.ByteString getAid();

    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code TransitCreateParam}
   */
  public  static final class TransitCreateParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransitCreateParam)
      TransitCreateParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransitCreateParam.newBuilder() to construct.
    private TransitCreateParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransitCreateParam() {
      aid_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransitCreateParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              aid_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.Builder.class);
    }

    private int bitField0_;
    public static final int AID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString aid_;
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    public boolean hasAid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    public com.google.protobuf.ByteString getAid() {
      return aid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *卡名
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, aid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, aid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam) obj;

      boolean result = true;
      result = result && (hasAid() == other.hasAid());
      if (hasAid()) {
        result = result && getAid()
            .equals(other.getAid());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAid()) {
        hash = (37 * hash) + AID_FIELD_NUMBER;
        hash = (53 * hash) + getAid().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransitCreateParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransitCreateParam)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        aid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateParam_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.aid_ = aid_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.aid_ = com.google.protobuf.ByteString.EMPTY;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000002;
        } else {
          result.name_ = "";
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam.getDefaultInstance()) return this;
        if (other.hasAid()) {
          setAid(other.getAid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAid()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString aid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public boolean hasAid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public com.google.protobuf.ByteString getAid() {
        return aid_;
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public Builder setAid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public Builder clearAid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aid_ = getDefaultInstance().getAid();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卡名
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransitCreateParam)
    }

    // @@protoc_insertion_point(class_scope:TransitCreateParam)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransitCreateParam>
        PARSER = new com.google.protobuf.AbstractParser<TransitCreateParam>() {
      @java.lang.Override
      public TransitCreateParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransitCreateParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransitCreateParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransitCreateParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransitCreateAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransitCreateAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code TransitCreateAck}
   */
  public  static final class TransitCreateAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransitCreateAck)
      TransitCreateAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransitCreateAck.newBuilder() to construct.
    private TransitCreateAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransitCreateAck() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransitCreateAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck) obj;

      boolean result = true;
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransitCreateAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransitCreateAck)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitCreateAck_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransitCreateAck)
    }

    // @@protoc_insertion_point(class_scope:TransitCreateAck)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransitCreateAck>
        PARSER = new com.google.protobuf.AbstractParser<TransitCreateAck>() {
      @java.lang.Override
      public TransitCreateAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransitCreateAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransitCreateAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransitCreateAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitCreateAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransitRechargeParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransitRechargeParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    boolean hasAid();
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    com.google.protobuf.ByteString getAid();
  }
  /**
   * Protobuf type {@code TransitRechargeParam}
   */
  public  static final class TransitRechargeParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransitRechargeParam)
      TransitRechargeParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransitRechargeParam.newBuilder() to construct.
    private TransitRechargeParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransitRechargeParam() {
      aid_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransitRechargeParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              aid_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.Builder.class);
    }

    private int bitField0_;
    public static final int AID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString aid_;
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    public boolean hasAid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *aid
     * </pre>
     *
     * <code>required bytes aid = 1;</code>
     */
    public com.google.protobuf.ByteString getAid() {
      return aid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, aid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, aid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam) obj;

      boolean result = true;
      result = result && (hasAid() == other.hasAid());
      if (hasAid()) {
        result = result && getAid()
            .equals(other.getAid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAid()) {
        hash = (37 * hash) + AID_FIELD_NUMBER;
        hash = (53 * hash) + getAid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransitRechargeParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransitRechargeParam)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        aid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeParam_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.aid_ = aid_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.aid_ = com.google.protobuf.ByteString.EMPTY;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam.getDefaultInstance()) return this;
        if (other.hasAid()) {
          setAid(other.getAid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAid()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString aid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public boolean hasAid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public com.google.protobuf.ByteString getAid() {
        return aid_;
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public Builder setAid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *aid
       * </pre>
       *
       * <code>required bytes aid = 1;</code>
       */
      public Builder clearAid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aid_ = getDefaultInstance().getAid();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransitRechargeParam)
    }

    // @@protoc_insertion_point(class_scope:TransitRechargeParam)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransitRechargeParam>
        PARSER = new com.google.protobuf.AbstractParser<TransitRechargeParam>() {
      @java.lang.Override
      public TransitRechargeParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransitRechargeParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransitRechargeParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransitRechargeParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransitRechargeAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransitRechargeAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code TransitRechargeAck}
   */
  public  static final class TransitRechargeAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransitRechargeAck)
      TransitRechargeAckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransitRechargeAck.newBuilder() to construct.
    private TransitRechargeAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransitRechargeAck() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransitRechargeAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *错误码, 0:成功
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck)) {
        return super.equals(obj);
      }
      com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck other = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck) obj;

      boolean result = true;
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransitRechargeAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransitRechargeAck)
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeAck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.class, com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.Builder.class);
      }

      // Construct using com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.internal_static_TransitRechargeAck_descriptor;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck getDefaultInstanceForType() {
        return com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.getDefaultInstance();
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck build() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck buildPartial() {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck result = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck) {
          return mergeFrom((com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck other) {
        if (other == com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误码, 0:成功
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransitRechargeAck)
    }

    // @@protoc_insertion_point(class_scope:TransitRechargeAck)
    private static final com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck();
    }

    public static com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransitRechargeAck>
        PARSER = new com.google.protobuf.AbstractParser<TransitRechargeAck>() {
      @java.lang.Override
      public TransitRechargeAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransitRechargeAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransitRechargeAck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransitRechargeAck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ryeex.groot.lib.ble.stack.pb.entity.PBTransit.TransitRechargeAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransitCreateParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransitCreateParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransitCreateAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransitCreateAck_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransitRechargeParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransitRechargeParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransitRechargeAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransitRechargeAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTransit.proto\"/\n\022TransitCreateParam\022\013\n" +
      "\003aid\030\001 \002(\014\022\014\n\004name\030\002 \002(\t\" \n\020TransitCreat" +
      "eAck\022\014\n\004code\030\001 \002(\005\"#\n\024TransitRechargePar" +
      "am\022\013\n\003aid\030\001 \002(\014\"\"\n\022TransitRechargeAck\022\014\n" +
      "\004code\030\001 \002(\005B4\n\'com.ryeex.groot.lib.ble.s" +
      "tack.pb.entityB\tPBTransit"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransitCreateParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransitCreateParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransitCreateParam_descriptor,
        new java.lang.String[] { "Aid", "Name", });
    internal_static_TransitCreateAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransitCreateAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransitCreateAck_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_TransitRechargeParam_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TransitRechargeParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransitRechargeParam_descriptor,
        new java.lang.String[] { "Aid", });
    internal_static_TransitRechargeAck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TransitRechargeAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransitRechargeAck_descriptor,
        new java.lang.String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
